#![doc = include_str!("../README.md")]

pub mod acp;
pub mod client;
pub(crate) mod color;
pub mod credentials;
pub mod error;
pub(crate) mod file_changes;
pub mod generate_command;
pub mod headless;
pub mod init;
pub mod log_format;
pub mod log_level;
pub mod mcp_command;
pub mod mcp_config_args;
pub mod output;
pub(crate) mod progress;
pub(crate) mod prompt;
pub mod provider_connection_args;
pub(crate) mod provider_stall;
pub mod resolve;
pub(crate) mod run_max_tokens;
pub(crate) mod run_timeout;
pub(crate) mod run_usage;
pub mod runtime;
pub mod sandbox;
pub mod settings;
pub mod settings_args;
pub mod show_prompt;
pub(crate) mod slash_commands;
pub(crate) mod telemetry;
pub mod transcript;
pub mod version;
pub mod workspace;

pub use acp::map_mcp_prompt_to_available_command;
